version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: teetli_pg
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - teetli_pgdata:/var/lib/postgresql/data

volumes:
  teetli_pgdata: