"""update candidates table with new columns

Revision ID: 59ac9ecb724b
Revises: a96e8f4a6398
Create Date: 2025-09-24 15:50:30.676964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ac9ecb724b'
down_revision: Union[str, Sequence[str], None] = 'a96e8f4a6398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
