"""Add user relationships to Job model

Revision ID: 7875d4e1d47a
Revises: c7b8fe4c1e85
Create Date: 2025-11-03 16:15:01.271178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7875d4e1d47a'
down_revision: Union[str, Sequence[str], None] = 'c7b8fe4c1e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
