"""add new table or column

Revision ID: 83a8f9b3b8b0
Revises: cac2c1d7cc28
Create Date: 2025-08-23 11:51:44.477781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a8f9b3b8b0'
down_revision: Union[str, Sequence[str], None] = 'cac2c1d7cc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
