"""Add ai_score and ai_explanation columns to candidates

Revision ID: a96e8f4a6398
Revises: 97034c3c8b40
Create Date: 2025-09-03 18:11:38.325673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96e8f4a6398'
down_revision: Union[str, Sequence[str], None] = '97034c3c8b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('ai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'ai_explanation')
    op.drop_column('candidates', 'ai_score')
    # ### end Alembic commands ###
