"""Add user relationships to Job model

Revision ID: c7b8fe4c1e85
Revises: d8210c737cc6
Create Date: 2025-11-03 14:37:08.075882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7b8fe4c1e85'
down_revision: Union[str, Sequence[str], None] = 'd8210c737cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workup_google_oauth_tokens_id'), table_name='workup_google_oauth_tokens')
    op.drop_index(op.f('ix_workup_google_oauth_tokens_user_id'), table_name='workup_google_oauth_tokens')
    op.drop_table('workup_google_oauth_tokens')
    op.drop_index(op.f('ix_impersonations_id'), table_name='impersonations')
    op.drop_index(op.f('ix_impersonations_token'), table_name='impersonations')
    op.drop_table('impersonations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impersonations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('impersonations_admin_id_fkey')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('impersonations_target_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('impersonations_pkey'))
    )
    op.create_index(op.f('ix_impersonations_token'), 'impersonations', ['token'], unique=True)
    op.create_index(op.f('ix_impersonations_id'), 'impersonations', ['id'], unique=False)
    op.create_table('workup_google_oauth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workup_google_oauth_tokens_pkey'))
    )
    op.create_index(op.f('ix_workup_google_oauth_tokens_user_id'), 'workup_google_oauth_tokens', ['user_id'], unique=True)
    op.create_index(op.f('ix_workup_google_oauth_tokens_id'), 'workup_google_oauth_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
