"""add ctc column to candidates

Revision ID: c7c3f1085f10
Revises: 59ac9ecb724b
Create Date: 2025-09-24 16:36:42.480970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c3f1085f10'
down_revision: Union[str, Sequence[str], None] = '59ac9ecb724b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('ctc', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'ctc')
    # ### end Alembic commands ###
