"""Vendor table

Revision ID: d81c4f3bce85
Revises: 
Create Date: 2025-08-25 01:44:26.323600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81c4f3bce85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_index(op.f('ix_managers_manager_id'), 'managers', ['manager_id'], unique=False)
    op.add_column('candidate_jd_mapping', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_constraint(op.f('jobs_client_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'jobs', 'managers', ['manager_id'], ['manager_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_client_id_fkey'), 'jobs', 'clients', ['client_id'], ['client_id'])
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('jobs', 'manager_id')
    op.drop_column('candidate_jd_mapping', 'status')
    op.drop_index(op.f('ix_managers_manager_id'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
